### ISSUE TITLE
Emergency

### ISSUE THREAD

**Issue by mraunt** [Deployd1/Astronomical-Grabber-Builder#1]
How can i speak to you privatly?

**Comment by Deployd1** [comment]
I dont do hacking stuff anymore but you remembered me of this Project, i will start again and bring a better Tool out in some weeks. What is the issue?

**Comment by Deployd1** [comment]
Deployd#4556

**Comment by mraunt** [comment]
I want to access to my account. I dont want to do this. Just teach me how
to do it or give me a script. Its very safe site

**Comment by Deployd1** [comment]
what  are you talking

**Comment by mraunt** [comment]
I want to access to my account in a site can you help me with that?

**Comment by Deployd1** [comment]
no wtf
